version: "3.8"

services:
  auth_server:
    image: python:3.10-alpine
    container_name: auth_server
    user: root
    environment:
      DATABASE_URL: sqlite:///projectdb2.db
    volumes:
      - ./auth:/auth
      - ./dal:/dal
      - ./common:/common
      - ./projectdb2.db:/projectdb2.db
      - ./requirements.txt:/requirements.txt
    command: sh -c "pip install -r /requirements.txt && python /auth/server.py"
    networks:
      my_lan:
        ipv4_address: "182.20.1.3"
    ports:
      - "5000:5000"
    

  db_server:
    image: python:3.10-alpine
    container_name: db_server
    user: root
    environment:
      DATABASE_URL: sqlite:///projectdb2.db
    volumes:
      - ./dal:/dal
      - ./common:/common
      - ./requirements.txt:/requirements.txt
      - ./projectdb2.db:/projectdb2.db
    command: sh -c "pip install -r /requirements.txt && python /dal/server.py"
    networks:
      my_lan:
        ipv4_address: "182.20.1.4"
    ports:
      - "5001:5001"
  
  gateway_server:
    image: python:3.10-alpine
    container_name: gateway_server
    user: root
    volumes:
      - ./gateway:/gateway
      - ./dal:/dal
      - ./common:/common
      - ./requirements.txt:/requirements.txt
    command: sh -c "pip install -r /requirements.txt && python /gateway/server.py"
    networks:
      my_lan:
        ipv4_address: "182.20.1.2"
    ports:
      - "5002:5002"

  notification_server:
    image: python:3.10-alpine
    container_name: notification_server
    user: root
    volumes:
      - ./notification:/notification
      - ./common:/common
      - ./requirements.txt:/requirements.txt
    command: sh -c "pip install -r /requirements.txt && python /notification/server.py"
    networks:
      my_lan:
        ipv4_address: "182.20.1.6"
    ports:
      - "5003:5003"

  frontend:
    image: nginx:alpine  # Use the official Nginx image
    ports:
      - "8080:80"  # Map port 80 in the container to port 8080 on the host
    volumes:
      - ./frontend-html:/usr/share/nginx/html:ro  # Mount your frontend files into the Nginx HTML directory
    

  client:
    image: python:3.10-alpine
    container_name: client
    user: root
    volumes:
      - ./notification:/notification
      - ./requirements.txt:/requirements.txt
    command: sh -c "pip install -r /requirements.txt && python /notification/client.py"
    networks:
      my_lan:
        ipv4_address: "182.20.1.9"
        
networks:
  my_lan:
    driver: bridge
    ipam:
      config:
        - subnet: 182.20.0.0/16